### ISSUE TITLE
Character encoding issue on Windows 10

### ISSUE THREAD

**Issue by ncook-hxgn** [matthewb66/detect-wizard#11]
I'm trying to use the detect-wizard to generate some recommendations for a project, using the following command in PowerShell 5.1 with python 3.11 - I installed according to the README.md here, and #8.

`detect-wizard --sensitivity 3 --focus l --url $Url --api_token $Token --no_scan --hub_project "Scan-Test" --hub_version "<my-project>.DetectWizard.LicenseFocus.DefaultParams" "D:\\repos\\<company>\\<my-project>"`

When I run the command, I get the output below back. I had a quick look at the sources, and it's failing where it's trying to create a log file.

```cmd
C:\Users\ncook>detect-wizard --sensitivity 3 --focus l --url $Url --api_token $Token --no_scan --hub_project "Scan-Test" --hub_version "MyProject.DetectWizard.LicenseFocus.DefaultParams" "D:\\repos\\<company>\\<my-project>"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ncook\AppData\Local\Programs\Python\Python311\Scripts\detect-wizard.exe\__main__.py", line 7, in <module>
  File "C:\Users\ncook\AppData\Local\Programs\Python\Python311\Lib\site-packages\detect_wizard_src\detect_wizard.py", line 2171, in run
    input_log_file.write(line + "\n")
  File "C:\Users\ncook\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>

C:\Users\ncook>
```

The log file does get created, it looks like this:
```
Scan Dir: D:\\repos\\<company>\\<my-project>
Sensitivity: 3
Focus: l
Trust cert: n

Scan Folder File Tree --
<my-project>/
```

Do you have any advice on things I could improve in my command, or is there something obviously wrong? (The version is a bit of a silly one, but I've got my reasons..)

Thanks :)

**Comment by ncook-hxgn** [comment]
I tried to configure python's IO encoding using environment variables, a suggestion I found on [StackOverFlow](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters/63573649#63573649).

```pwsh
$Env:PYTHONLEGACYWINDOWSSTDIO="windows-1252"
$Env:PYTHONIOENCODING="windows-1252"
```

It didn't work, this yields the same error as OP, and so does the below:

```pwsh
$Env:PYTHONIOENCODING="utf-8"
$Env:PYTHONLEGACYWINDOWSSTDIO="utf-8"
```

**Comment by ncook-hxgn** [comment]
I got the same error when I ran detect-wizard with no arguments (sic: interactive mode) and entered them manually, too. :(
